### PR TITLE
Ready for Release v0.3.0 / Support Redmine 4.0

### PR DESCRIPTION
**Pull request by akiko-pusu**
**Todo:**

- [x] Update Readme
- [x]  Update version
- [x]  Update CI
- [x] Documentation
- [x] Create branch to support (maintenance) Redmine3.x, versioned 0.2.x.
  - https://github.com/akiko-pusu/redmine_issue_templates/tree/v0.2.x-support-Redmine3
- [x] Show custom message when Redmine3.x user try to install Latest issue template
  - commit: 
e0de195

### CODE REVIEW

**Comment by akiko-pusu** [comment]
Code verification, review, vote or any comments are highly appreciated!

**Comment by vividtone** [comment]
Thank you for working so hard on migrating the great plugin to Redmine 4.0! I will test this branch.

**Comment by akiko-pusu** [comment]
いったんここで様子見します！

**Comment by akiko-pusu** [comment]
**NOTE:** 

- In case using SQLite3 be careful to deal with boolean value, not only this plugin’s tables but also any other tables for Redmine. Since Rails5.2 there are some change to SQLite3.
  - ``Change sqlite3 boolean serialization to use 1 and 0.``
  - https://github.com/rails/rails/blob/v5.2.0/activerecord/CHANGELOG.md

SQLite3のBooleanの値の設定の方法がRails5.2から変わりました。
新規でカラム追加やデータの更新の場合は問題ないのですが、前からSQLite3を使っていてアップデートした場合は、Booleanの値として t or f が入っている。
こちらを 1 or 0 に修正しないと、フラグ系（enable / disable, default / not_default, inherit )あたりがうまく動作しません。

このへんはちょっとREADMEかリリースノートに触れておく。

**Comment by akiko-pusu** [comment]
On commit: 1c40149, add spec / test to confirm error message when creates template without mandatory field.
This test will be passed with applying https://github.com/ishikawa999/redmine_issue_templates/commit/ff422207c2452400cec544da987f75a8c3d6dcf1 :)
I do hope to apply @ishikawa999 san’s commit, and looking forward to pull request into dev branch.

**Comment by akiko-pusu** [comment]
@ishikawa999 Thank you so much for your PR!
All tests are completed: https://circleci.com/gh/akiko-pusu/redmine_issue_templates/238 :)
Now merge and close this issue.

**Pull request merged**
