### PR TITLE
Do not append template contents if the content hasn't been edited

### PR DESCRIPTION
**Pull request by dcotet**

### CODE REVIEW

**Comment by akiko-pusu** [comment]
Hi, @dcotet
I really appreciated your pull request!
Please wait for a while because I hope to add spec (e2e) for this.

**Comment by dcotet** [comment]
Its a pleasure to contribute to your code @akiko-pusu .

How many time do you mean per "wait for a while" ?

And what spec e2e means ?

Thank you very much and have a great day.

**Comment by akiko-pusu** [comment]
Hi, I’m so sorry to apply your pull request.
This patch was applied into b59ff6117b7f78 and merged into master branch.
Thank you so much for your support!

**Comment by dcotet** [comment]
Aww yeahh thank you very much that is my first free software contribution !!!

Have a great day and thanks again !

**Pull request closed without merging**
