### PR TITLE
[WIP] Add template for note

### PR DESCRIPTION
**Pull request by akiko-pusu**
Rails5 / Redmine4対応のブランチに、追加でnoteのテンプレートを実装してみる。
うまくいかなかったら見送り。

### CODE REVIEW

**Comment by sfabirovskiy** [comment]
Hello,
I am using your "Redmine issue templates" plugin in my company for a long time and we want to ask you about one thing.
We are interested by this https://github.com/akiko-pusu/redmine_issue_templates/pull/172  feature.
Do you know, will you plan to finish this one?
Templates for notes can be very useful e.g. for support teams which have to use template responses very often.
Thanks a lot.

**Comment by akiko-pusu** [comment]
Hi, @sfabirovskiy Thanks for your comment.
I do hope to implement this feature. 

> Templates for notes can be very useful e.g. for support teams which have to use template responses very often.

I completely agree above. 
I'm motivated thanks to your comment!

**Comment by akiko-pusu** [comment]
Related: #196

**Comment by akiko-pusu** [comment]
@sfabirovskiy I'm going to restart implement this feature at #223.

**Pull request closed without merging**
